### ISSUE TITLE
Random login credential failure

### ISSUE THREAD

**Issue by mtdukes** [anthonydb/pneumatic#19]
Running pneumatic will generate the following error, despite having the correct credentials:

`ERROR: Your username or password seems to be incorrect.
Please check them and try again.`

Seems to happen randomly. It will throw this error one time, then work a few minutes later.

**Comment by anthonydb** [comment]
Thanks for the report, @mtdukes. I'll see whether I can replicate. I probably should reach out to the Muckrock guys and ask whether they're making changes to the API.

**Comment by anthonydb** [comment]
@mtdukes I've changed the way pneumatic authenticates users via Requests, per the issue in https://github.com/anthonydb/pneumatic/issues/20. That should also fix this issue. If not, it may be an issue with the API? 

Also, I believe the MuckRack team is going to be updating its API in the future, so I'll likely need to do some refactoring of pneumatic as a result.
